/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Form;
import java.awt.HeadlessException;
import java.sql.*;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Data_item extends javax.swing.JFrame {
    
    public Statement st;
    public PreparedStatement ps;
    public ResultSet rs;
    Connection conn=Config.Koneksi.koneksiDB();
    
    public Data_item() {
        initComponents();
        showdata();
        reset();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_nama = new javax.swing.JTextField();
        txt_harga = new javax.swing.JTextField();
        Btn_hapus = new javax.swing.JButton();
        Btn_edit = new javax.swing.JButton();
        Btn_reset = new javax.swing.JButton();
        Btn_simpan = new javax.swing.JButton();
        cmb_kategori = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tbl_item = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Data Item");

        jLabel2.setText("Nama item");

        jLabel3.setText("Harga");

        jLabel4.setText("Kategori");

        txt_harga.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_hargaKeyReleased(evt);
            }
        });

        Btn_hapus.setText("Hapus");
        Btn_hapus.addActionListener(this::Btn_hapusActionPerformed);

        Btn_edit.setText("Edit");

        Btn_reset.setText("Reset");
        Btn_reset.addActionListener(this::Btn_resetActionPerformed);

        Btn_simpan.setText("Simpan");
        Btn_simpan.addActionListener(this::Btn_simpanActionPerformed);

        cmb_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tidak ada", "Makanan", "Minuman" }));
        cmb_kategori.addItemListener(this::cmb_kategoriItemStateChanged);
        cmb_kategori.addActionListener(this::cmb_kategoriActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmb_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Btn_hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_edit)
                        .addGap(79, 79, 79)
                        .addComponent(Btn_reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_harga, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmb_kategori, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_harga, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_hapus)
                    .addComponent(Btn_edit)
                    .addComponent(Btn_simpan)
                    .addComponent(Btn_reset))
                .addContainerGap())
        );

        Tbl_item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama item", "Kategori", "Harga"
            }
        ));
        Tbl_item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Tbl_itemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tbl_item);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(479, 479, 479))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_resetActionPerformed
        reset();
    }//GEN-LAST:event_Btn_resetActionPerformed

    private void cmb_kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_kategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_kategoriActionPerformed

    private void FormatRupiah(){
         if(!txt_harga.getText().equals("")){
          String Replace=txt_harga.getText().replaceAll("[^\\d]", "");
          double FormatRp=Double.parseDouble(Replace);
          DecimalFormat dcf=new DecimalFormat("#,###,###");
          txt_harga.setText(dcf.format(FormatRp));
         }
    }
    
    
    private void Btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_simpanActionPerformed
        if(txt_nama.getText().equals("")||txt_harga.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Data yang akan dimasukkan belum lengkap !", "Validasi", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            st=conn.createStatement();
            if(Btn_simpan.getText()=="Simpan"){
                String find="SELECT * FROM tbl_dataItem WHERE nama_item='"+ txt_nama.getText() +"' ";
                rs=st.executeQuery(find);
                if(rs.next()){
                    JOptionPane.showMessageDialog(null, "Menu sudah pernah dimasukkan, silahkan masukkan menu lain", "Validasi", JOptionPane.WARNING_MESSAGE);
                }else{
                      String nama=txt_nama.getText();
                      String kategori=cmb_kategori.getItemAt(cmb_kategori.getSelectedIndex());
                      String harga=txt_harga.getText();
                      String ReplaceHarga=harga.replaceAll(",", "");
                      
                      String sql="INSERT INTO tbl_dataItem (nama_item,kategori,harga) VALUES(?,?,?)";
                      ps=conn.prepareStatement(sql);
                      ps.setString(1, nama);
                      ps.setString(2, kategori);
                      ps.setString(3, ReplaceHarga);
                      
                      ps.executeUpdate();
                      JOptionPane.showMessageDialog(null, "Data berhasil di simpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                      showdata();
                      
                }
            }else{
                      int selectedRow=Tbl_item.getSelectedRow();
                      String No=Tbl_item.getValueAt(selectedRow, 0).toString();
                      String nama=txt_nama.getText();
                      String kategori=cmb_kategori.getItemAt(cmb_kategori.getSelectedIndex());
                      String harga=txt_harga.getText();
                      String ReplaceHarga=harga.replaceAll(",", "");
                      
                      String sql="UPDATE tbl_dataItem SET nama_item=?, kategori=?, harga=? WHERE No=? ";
                      ps=conn.prepareStatement(sql);
                      ps.setString(1, nama);
                      ps.setString(2, kategori);
                      ps.setString(3, ReplaceHarga);
                      ps.setString(4, No);
                      
                      ps.executeUpdate();
                      JOptionPane.showMessageDialog(null, "Data berhasil di Update", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                      showdata();
                      reset();
            }
        } catch (HeadlessException | SQLException e) {
        }
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_Btn_simpanActionPerformed

    private void cmb_kategoriItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_kategoriItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_kategoriItemStateChanged

    private void Tbl_itemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Tbl_itemMouseClicked
        DefaultTableModel model=(DefaultTableModel)Tbl_item.getModel();
        int selectedRow=Tbl_item.getSelectedRow();
        
        txt_nama.setText(model.getValueAt(selectedRow, 1).toString());
        String colKat=model.getValueAt(selectedRow, 2).toString();
        for(int i=0;i<cmb_kategori.getItemCount();i++){
            if(cmb_kategori.getItemAt(i).toString().equalsIgnoreCase(colKat)){
            cmb_kategori.setSelectedIndex(i);
            }
    }
        txt_harga.setText(model.getValueAt(selectedRow, 3).toString());
        Btn_simpan.setText("Update");
        FormatRupiah();
    }//GEN-LAST:event_Tbl_itemMouseClicked

    private void Btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_hapusActionPerformed
        try {
            if(txt_nama.getText().equals("")||txt_nama.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Silahkan pilih data yang akan dihapus", "Validasi", JOptionPane.INFORMATION_MESSAGE);
            }else{
                int konfirmasi= JOptionPane.showConfirmDialog(null, "Anda ingin menghapus data, ingin melanjutkan ?", "Hapus data", JOptionPane.YES_NO_OPTION);
                if(konfirmasi==0){
                    int selectedRow=Tbl_item.getSelectedRow();
                    String No=Tbl_item.getValueAt (selectedRow, 0).toString();
                    String sql="DELETE FROM tbl_dataItem WHERE No=?";
                    ps=conn.prepareStatement(sql);
                    ps.setString(1, No);
                    ps.executeUpdate();
                    showdata();
                    reset();
                }else{
                    reset();
                }
                
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_Btn_hapusActionPerformed

    private void txt_hargaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_hargaKeyReleased
            FormatRupiah();
    }//GEN-LAST:event_txt_hargaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Data_item().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_edit;
    private javax.swing.JButton Btn_hapus;
    private javax.swing.JButton Btn_reset;
    private javax.swing.JButton Btn_simpan;
    private javax.swing.JTable Tbl_item;
    private javax.swing.JComboBox<String> cmb_kategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_harga;
    private javax.swing.JTextField txt_nama;
    // End of variables declaration//GEN-END:variables

    private void showdata() {
        DefaultTableModel model=(DefaultTableModel)Tbl_item.getModel();
        model.setRowCount(0);
        try {
            String sql="SELECT * FROM tbl_dataItem";
            ps=conn.prepareStatement(sql);
            rs=ps.executeQuery(sql);
            while(rs.next()){
                int no=rs.getInt("No");
                String nama=rs.getString("nama_item");
                String kategori=rs.getString("kategori");
                String harga=rs.getString("harga");
       
                Object[] Rowdata={nama,kategori,harga};
                model.addRow(Rowdata);
                
            }
        } catch (SQLException e) {
        }
    
    }

    private void reset() {
        txt_nama.setText("");
        cmb_kategori.setSelectedIndex(0);
        txt_harga.setText("");
        Btn_simpan.setText("Simpan");
    }
}
